/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HelpRouteRouteImport } from './routes/help/route'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as SettingsRouteRouteImport } from './routes/settings/route'
import { Route as HelpIndexRouteImport } from './routes/help/index'
import { Route as HelpChapterRouteImport } from './routes/help/$chapter'
import { Route as OOrgRouteImport } from './routes/o.$org'
import { Route as PProjRouteRouteImport } from './routes/p.$proj/route'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as SettingsGatesRouteImport } from './routes/settings/gates'
import { Route as SettingsMembersRouteImport } from './routes/settings/members'
import { Route as SettingsTokensRouteImport } from './routes/settings/tokens'
import { Route as SettingsWorkspaceRouteImport } from './routes/settings/workspace'
import { Route as PProjIndexRouteImport } from './routes/p.$proj/index'
import { Route as PProjReviewsIndexRouteImport } from './routes/p.$proj/reviews.index'
import { Route as PProjSessionsIndexRouteImport } from './routes/p.$proj/sessions.index'
import { Route as PProjSessionsSessionRouteImport } from './routes/p.$proj/sessions.$session'
import { Route as PProjSpecsIndexRouteImport } from './routes/p.$proj/specs.index'
import { Route as PProjSpecsSpecRouteImport } from './routes/p.$proj/specs.$spec'
import { Route as PProjTasksIndexRouteImport } from './routes/p.$proj/tasks.index'
import { Route as PProjTasksTaskRouteImport } from './routes/p.$proj/tasks.$task'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRouteRoute = HelpRouteRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRouteRoute = SettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpIndexRoute = HelpIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HelpRouteRoute,
} as any)
const HelpChapterRoute = HelpChapterRouteImport.update({
  id: '/$chapter',
  path: '/$chapter',
  getParentRoute: () => HelpRouteRoute,
} as any)
const OOrgRoute = OOrgRouteImport.update({
  id: '/o/$org',
  path: '/o/$org',
  getParentRoute: () => rootRouteImport,
} as any)
const PProjRouteRoute = PProjRouteRouteImport.update({
  id: '/p/$proj',
  path: '/p/$proj',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsGatesRoute = SettingsGatesRouteImport.update({
  id: '/gates',
  path: '/gates',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsMembersRoute = SettingsMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsTokensRoute = SettingsTokensRouteImport.update({
  id: '/tokens',
  path: '/tokens',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsWorkspaceRoute = SettingsWorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const PProjIndexRoute = PProjIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PProjRouteRoute,
} as any)
const PProjReviewsIndexRoute = PProjReviewsIndexRouteImport.update({
  id: '/reviews/',
  path: '/reviews/',
  getParentRoute: () => PProjRouteRoute,
} as any)
const PProjSessionsIndexRoute = PProjSessionsIndexRouteImport.update({
  id: '/sessions/',
  path: '/sessions/',
  getParentRoute: () => PProjRouteRoute,
} as any)
const PProjSessionsSessionRoute = PProjSessionsSessionRouteImport.update({
  id: '/sessions/$session',
  path: '/sessions/$session',
  getParentRoute: () => PProjRouteRoute,
} as any)
const PProjSpecsIndexRoute = PProjSpecsIndexRouteImport.update({
  id: '/specs/',
  path: '/specs/',
  getParentRoute: () => PProjRouteRoute,
} as any)
const PProjSpecsSpecRoute = PProjSpecsSpecRouteImport.update({
  id: '/specs/$spec',
  path: '/specs/$spec',
  getParentRoute: () => PProjRouteRoute,
} as any)
const PProjTasksIndexRoute = PProjTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => PProjRouteRoute,
} as any)
const PProjTasksTaskRoute = PProjTasksTaskRouteImport.update({
  id: '/tasks/$task',
  path: '/tasks/$task',
  getParentRoute: () => PProjRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/help': typeof HelpRouteRouteWithChildren
  '/settings': typeof SettingsRouteRouteWithChildren
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/p/$proj': typeof PProjRouteRouteWithChildren
  '/help/$chapter': typeof HelpChapterRoute
  '/o/$org': typeof OOrgRoute
  '/settings/gates': typeof SettingsGatesRoute
  '/settings/members': typeof SettingsMembersRoute
  '/settings/tokens': typeof SettingsTokensRoute
  '/settings/workspace': typeof SettingsWorkspaceRoute
  '/help/': typeof HelpIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/p/$proj/': typeof PProjIndexRoute
  '/p/$proj/sessions/$session': typeof PProjSessionsSessionRoute
  '/p/$proj/specs/$spec': typeof PProjSpecsSpecRoute
  '/p/$proj/tasks/$task': typeof PProjTasksTaskRoute
  '/p/$proj/reviews/': typeof PProjReviewsIndexRoute
  '/p/$proj/sessions/': typeof PProjSessionsIndexRoute
  '/p/$proj/specs/': typeof PProjSpecsIndexRoute
  '/p/$proj/tasks/': typeof PProjTasksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/help/$chapter': typeof HelpChapterRoute
  '/o/$org': typeof OOrgRoute
  '/settings/gates': typeof SettingsGatesRoute
  '/settings/members': typeof SettingsMembersRoute
  '/settings/tokens': typeof SettingsTokensRoute
  '/settings/workspace': typeof SettingsWorkspaceRoute
  '/help': typeof HelpIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/p/$proj': typeof PProjIndexRoute
  '/p/$proj/sessions/$session': typeof PProjSessionsSessionRoute
  '/p/$proj/specs/$spec': typeof PProjSpecsSpecRoute
  '/p/$proj/tasks/$task': typeof PProjTasksTaskRoute
  '/p/$proj/reviews': typeof PProjReviewsIndexRoute
  '/p/$proj/sessions': typeof PProjSessionsIndexRoute
  '/p/$proj/specs': typeof PProjSpecsIndexRoute
  '/p/$proj/tasks': typeof PProjTasksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/help': typeof HelpRouteRouteWithChildren
  '/settings': typeof SettingsRouteRouteWithChildren
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/p/$proj': typeof PProjRouteRouteWithChildren
  '/help/$chapter': typeof HelpChapterRoute
  '/o/$org': typeof OOrgRoute
  '/settings/gates': typeof SettingsGatesRoute
  '/settings/members': typeof SettingsMembersRoute
  '/settings/tokens': typeof SettingsTokensRoute
  '/settings/workspace': typeof SettingsWorkspaceRoute
  '/help/': typeof HelpIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/p/$proj/': typeof PProjIndexRoute
  '/p/$proj/sessions/$session': typeof PProjSessionsSessionRoute
  '/p/$proj/specs/$spec': typeof PProjSpecsSpecRoute
  '/p/$proj/tasks/$task': typeof PProjTasksTaskRoute
  '/p/$proj/reviews/': typeof PProjReviewsIndexRoute
  '/p/$proj/sessions/': typeof PProjSessionsIndexRoute
  '/p/$proj/specs/': typeof PProjSpecsIndexRoute
  '/p/$proj/tasks/': typeof PProjTasksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/help'
    | '/settings'
    | '/inbox'
    | '/login'
    | '/notifications'
    | '/onboarding'
    | '/p/$proj'
    | '/help/$chapter'
    | '/o/$org'
    | '/settings/gates'
    | '/settings/members'
    | '/settings/tokens'
    | '/settings/workspace'
    | '/help/'
    | '/settings/'
    | '/p/$proj/'
    | '/p/$proj/sessions/$session'
    | '/p/$proj/specs/$spec'
    | '/p/$proj/tasks/$task'
    | '/p/$proj/reviews/'
    | '/p/$proj/sessions/'
    | '/p/$proj/specs/'
    | '/p/$proj/tasks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/inbox'
    | '/login'
    | '/notifications'
    | '/onboarding'
    | '/help/$chapter'
    | '/o/$org'
    | '/settings/gates'
    | '/settings/members'
    | '/settings/tokens'
    | '/settings/workspace'
    | '/help'
    | '/settings'
    | '/p/$proj'
    | '/p/$proj/sessions/$session'
    | '/p/$proj/specs/$spec'
    | '/p/$proj/tasks/$task'
    | '/p/$proj/reviews'
    | '/p/$proj/sessions'
    | '/p/$proj/specs'
    | '/p/$proj/tasks'
  id:
    | '__root__'
    | '/'
    | '/help'
    | '/settings'
    | '/inbox'
    | '/login'
    | '/notifications'
    | '/onboarding'
    | '/p/$proj'
    | '/help/$chapter'
    | '/o/$org'
    | '/settings/gates'
    | '/settings/members'
    | '/settings/tokens'
    | '/settings/workspace'
    | '/help/'
    | '/settings/'
    | '/p/$proj/'
    | '/p/$proj/sessions/$session'
    | '/p/$proj/specs/$spec'
    | '/p/$proj/tasks/$task'
    | '/p/$proj/reviews/'
    | '/p/$proj/sessions/'
    | '/p/$proj/specs/'
    | '/p/$proj/tasks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HelpRouteRoute: typeof HelpRouteRouteWithChildren
  SettingsRouteRoute: typeof SettingsRouteRouteWithChildren
  InboxRoute: typeof InboxRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  OnboardingRoute: typeof OnboardingRoute
  PProjRouteRoute: typeof PProjRouteRouteWithChildren
  OOrgRoute: typeof OOrgRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help/': {
      id: '/help/'
      path: '/'
      fullPath: '/help/'
      preLoaderRoute: typeof HelpIndexRouteImport
      parentRoute: typeof HelpRouteRoute
    }
    '/help/$chapter': {
      id: '/help/$chapter'
      path: '/$chapter'
      fullPath: '/help/$chapter'
      preLoaderRoute: typeof HelpChapterRouteImport
      parentRoute: typeof HelpRouteRoute
    }
    '/o/$org': {
      id: '/o/$org'
      path: '/o/$org'
      fullPath: '/o/$org'
      preLoaderRoute: typeof OOrgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$proj': {
      id: '/p/$proj'
      path: '/p/$proj'
      fullPath: '/p/$proj'
      preLoaderRoute: typeof PProjRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/gates': {
      id: '/settings/gates'
      path: '/gates'
      fullPath: '/settings/gates'
      preLoaderRoute: typeof SettingsGatesRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/members': {
      id: '/settings/members'
      path: '/members'
      fullPath: '/settings/members'
      preLoaderRoute: typeof SettingsMembersRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/tokens': {
      id: '/settings/tokens'
      path: '/tokens'
      fullPath: '/settings/tokens'
      preLoaderRoute: typeof SettingsTokensRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/workspace': {
      id: '/settings/workspace'
      path: '/workspace'
      fullPath: '/settings/workspace'
      preLoaderRoute: typeof SettingsWorkspaceRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/p/$proj/': {
      id: '/p/$proj/'
      path: '/'
      fullPath: '/p/$proj/'
      preLoaderRoute: typeof PProjIndexRouteImport
      parentRoute: typeof PProjRouteRoute
    }
    '/p/$proj/reviews/': {
      id: '/p/$proj/reviews/'
      path: '/reviews'
      fullPath: '/p/$proj/reviews/'
      preLoaderRoute: typeof PProjReviewsIndexRouteImport
      parentRoute: typeof PProjRouteRoute
    }
    '/p/$proj/sessions/': {
      id: '/p/$proj/sessions/'
      path: '/sessions'
      fullPath: '/p/$proj/sessions/'
      preLoaderRoute: typeof PProjSessionsIndexRouteImport
      parentRoute: typeof PProjRouteRoute
    }
    '/p/$proj/sessions/$session': {
      id: '/p/$proj/sessions/$session'
      path: '/sessions/$session'
      fullPath: '/p/$proj/sessions/$session'
      preLoaderRoute: typeof PProjSessionsSessionRouteImport
      parentRoute: typeof PProjRouteRoute
    }
    '/p/$proj/specs/': {
      id: '/p/$proj/specs/'
      path: '/specs'
      fullPath: '/p/$proj/specs/'
      preLoaderRoute: typeof PProjSpecsIndexRouteImport
      parentRoute: typeof PProjRouteRoute
    }
    '/p/$proj/specs/$spec': {
      id: '/p/$proj/specs/$spec'
      path: '/specs/$spec'
      fullPath: '/p/$proj/specs/$spec'
      preLoaderRoute: typeof PProjSpecsSpecRouteImport
      parentRoute: typeof PProjRouteRoute
    }
    '/p/$proj/tasks/': {
      id: '/p/$proj/tasks/'
      path: '/tasks'
      fullPath: '/p/$proj/tasks/'
      preLoaderRoute: typeof PProjTasksIndexRouteImport
      parentRoute: typeof PProjRouteRoute
    }
    '/p/$proj/tasks/$task': {
      id: '/p/$proj/tasks/$task'
      path: '/tasks/$task'
      fullPath: '/p/$proj/tasks/$task'
      preLoaderRoute: typeof PProjTasksTaskRouteImport
      parentRoute: typeof PProjRouteRoute
    }
  }
}

interface HelpRouteRouteChildren {
  HelpChapterRoute: typeof HelpChapterRoute
  HelpIndexRoute: typeof HelpIndexRoute
}

const HelpRouteRouteChildren: HelpRouteRouteChildren = {
  HelpChapterRoute: HelpChapterRoute,
  HelpIndexRoute: HelpIndexRoute,
}

const HelpRouteRouteWithChildren = HelpRouteRoute._addFileChildren(
  HelpRouteRouteChildren,
)

interface SettingsRouteRouteChildren {
  SettingsGatesRoute: typeof SettingsGatesRoute
  SettingsMembersRoute: typeof SettingsMembersRoute
  SettingsTokensRoute: typeof SettingsTokensRoute
  SettingsWorkspaceRoute: typeof SettingsWorkspaceRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteRouteChildren: SettingsRouteRouteChildren = {
  SettingsGatesRoute: SettingsGatesRoute,
  SettingsMembersRoute: SettingsMembersRoute,
  SettingsTokensRoute: SettingsTokensRoute,
  SettingsWorkspaceRoute: SettingsWorkspaceRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteRouteWithChildren = SettingsRouteRoute._addFileChildren(
  SettingsRouteRouteChildren,
)

interface PProjRouteRouteChildren {
  PProjIndexRoute: typeof PProjIndexRoute
  PProjSessionsSessionRoute: typeof PProjSessionsSessionRoute
  PProjSpecsSpecRoute: typeof PProjSpecsSpecRoute
  PProjTasksTaskRoute: typeof PProjTasksTaskRoute
  PProjReviewsIndexRoute: typeof PProjReviewsIndexRoute
  PProjSessionsIndexRoute: typeof PProjSessionsIndexRoute
  PProjSpecsIndexRoute: typeof PProjSpecsIndexRoute
  PProjTasksIndexRoute: typeof PProjTasksIndexRoute
}

const PProjRouteRouteChildren: PProjRouteRouteChildren = {
  PProjIndexRoute: PProjIndexRoute,
  PProjSessionsSessionRoute: PProjSessionsSessionRoute,
  PProjSpecsSpecRoute: PProjSpecsSpecRoute,
  PProjTasksTaskRoute: PProjTasksTaskRoute,
  PProjReviewsIndexRoute: PProjReviewsIndexRoute,
  PProjSessionsIndexRoute: PProjSessionsIndexRoute,
  PProjSpecsIndexRoute: PProjSpecsIndexRoute,
  PProjTasksIndexRoute: PProjTasksIndexRoute,
}

const PProjRouteRouteWithChildren = PProjRouteRoute._addFileChildren(
  PProjRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HelpRouteRoute: HelpRouteRouteWithChildren,
  SettingsRouteRoute: SettingsRouteRouteWithChildren,
  InboxRoute: InboxRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  OnboardingRoute: OnboardingRoute,
  PProjRouteRoute: PProjRouteRouteWithChildren,
  OOrgRoute: OOrgRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
