apiVersion: apps/v1
kind: Deployment
metadata:
  name: nerv-api
spec:
  template:
    spec:
      containers:
        - name: api
          resources:
            requests: { cpu: 500m, memory: 1Gi }
            limits: { memory: 2Gi }
