apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - { name: nerv-api, newTag: 'dev' }
  - { name: nerv-worker, newTag: 'dev' }
  - { name: nerv-web, newTag: 'dev' }
patches:
  - path: ingress-host.yaml
  - path: configmap-host.yaml
  - path: replicas.yaml
